#!/usr/bin/env python3
"""
Fetch the latest NIST OSCAL JSON files from usnistgov/oscal-content and
compare them against the checked-in copies in core/db/sources/.

Behavior:
  - If all files match (by SHA-256): exits 0, sets CHANGED=false
  - If any file differs: replaces files in core/db/sources/, writes a PR body
    to .github/pr-body.md, exits 0, sets CHANGED=true

GitHub Actions step outputs (written to $GITHUB_OUTPUT):
  changed       — 'true' or 'false'
  old_version   — version string from the existing catalog
  new_version   — version string from the newly downloaded catalog

Run from repo root:
    python scripts/fetch_nist_sources.py
"""

import hashlib
import json
import os
import sys
import urllib.request
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = REPO_ROOT / "core" / "db" / "sources"
PR_BODY_FILE = REPO_ROOT / ".github" / "pr-body.md"

# ── NIST source configuration ─────────────────────────────────────────────────
# Source: https://github.com/usnistgov/oscal-content
# Verify paths at: github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev5/json

NIST_RAW_BASE = (
    "https://raw.githubusercontent.com/usnistgov/oscal-content/main"
    "/nist.gov/SP800-53/rev5/json"
)

SOURCE_FILES = {
    "NIST_SP-800-53_rev5_catalog.json":
        f"{NIST_RAW_BASE}/NIST_SP-800-53_rev5_catalog.json",
    "NIST_SP-800-53_rev5_LOW-baseline-resolved-profile_catalog.json":
        f"{NIST_RAW_BASE}/NIST_SP-800-53_rev5_LOW-baseline-resolved-profile_catalog.json",
    "NIST_SP-800-53_rev5_MODERATE-baseline-resolved-profile_catalog.json":
        f"{NIST_RAW_BASE}/NIST_SP-800-53_rev5_MODERATE-baseline-resolved-profile_catalog.json",
    "NIST_SP-800-53_rev5_HIGH-baseline-resolved-profile_catalog.json":
        f"{NIST_RAW_BASE}/NIST_SP-800-53_rev5_HIGH-baseline-resolved-profile_catalog.json",
}

CATALOG_FILENAME = "NIST_SP-800-53_rev5_catalog.json"


# ── helpers ───────────────────────────────────────────────────────────────────

def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch(url: str) -> bytes:
    print(f"  Fetching {url.split('/')[-1]} ...")
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read()


def catalog_version(data: bytes) -> str:
    try:
        return json.loads(data)["catalog"]["metadata"]["version"]
    except (KeyError, json.JSONDecodeError):
        return "unknown"


def set_gha_output(key: str, value: str):
    """Write a key=value pair to $GITHUB_OUTPUT if running in GitHub Actions."""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{key}={value}\n")
    else:
        print(f"  [output] {key}={value}")


def write_pr_body(changes: list[dict], old_version: str, new_version: str):
    """Write a markdown PR description to .github/pr-body.md."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"## NIST 800-53 Catalog Sync — {today}",
        "",
        f"Automated weekly sync detected changes in the NIST OSCAL source files.",
        "",
        f"| | Version |",
        f"|---|---|",
        f"| **Before** | `{old_version}` |",
        f"| **After**  | `{new_version}` |",
        "",
        "### Changed Files",
        "",
    ]

    for c in changes:
        lines += [
            f"**`{c['filename']}`**",
            f"- Old SHA-256: `{c['old_hash']}`",
            f"- New SHA-256: `{c['new_hash']}`",
            "",
        ]

    lines += [
        "### What to Review",
        "",
        "- Check the diff on `core/db/sources/` for raw catalog changes",
        "- Check the diff on `core/db/seed/` for the regenerated SQL",
        "- Look for new or removed control IDs in `03-nist-controls.sql`",
        "- Verify `09-catalog-version.sql` reflects the new version and hash",
        "",
        "### Merging",
        "",
        "Merging this PR updates both the source JSONs and the generated SQL "
        "seed files atomically. Existing deployments will need to run the "
        "appropriate migration (see `core/db/migrations/`) to apply changes.",
        "",
        "_Generated by `.github/workflows/sync-nist.yml`_",
    ]

    PR_BODY_FILE.parent.mkdir(parents=True, exist_ok=True)
    PR_BODY_FILE.write_text("\n".join(lines) + "\n")
    print(f"  PR body written to {PR_BODY_FILE.relative_to(REPO_ROOT)}")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    print("Fetching NIST OSCAL source files...")
    downloaded: dict[str, bytes] = {}
    for filename, url in SOURCE_FILES.items():
        try:
            downloaded[filename] = fetch(url)
        except Exception as exc:
            print(f"ERROR: Failed to fetch {filename}: {exc}", file=sys.stderr)
            sys.exit(1)

    # Determine existing version before any replacements
    existing_catalog = (SOURCES_DIR / CATALOG_FILENAME)
    old_version = catalog_version(existing_catalog.read_bytes()) if existing_catalog.exists() else "none"
    new_version = catalog_version(downloaded[CATALOG_FILENAME])

    print(f"\nComparing hashes (existing → downloaded)...")
    changes = []
    for filename, new_data in downloaded.items():
        existing_path = SOURCES_DIR / filename
        old_hash = sha256(existing_path.read_bytes()) if existing_path.exists() else "none"
        new_hash = sha256(new_data)

        if old_hash == new_hash:
            print(f"  {filename}: unchanged")
        else:
            print(f"  {filename}: CHANGED")
            print(f"    old: {old_hash}")
            print(f"    new: {new_hash}")
            changes.append({
                "filename": filename,
                "old_hash": old_hash,
                "new_hash": new_hash,
            })

    if not changes:
        print("\nNo changes detected — catalog is up to date.")
        set_gha_output("changed", "false")
        set_gha_output("old_version", old_version)
        set_gha_output("new_version", new_version)
        return

    print(f"\n{len(changes)} file(s) changed. Updating core/db/sources/...")
    SOURCES_DIR.mkdir(parents=True, exist_ok=True)
    for filename, new_data in downloaded.items():
        (SOURCES_DIR / filename).write_bytes(new_data)
        print(f"  Updated {filename}")

    write_pr_body(changes, old_version, new_version)

    set_gha_output("changed", "true")
    set_gha_output("old_version", old_version)
    set_gha_output("new_version", new_version)


if __name__ == "__main__":
    main()
