-- NIST SP 800-53 Control Families
-- Auto-generated by scripts/convert_nist_oscal.py — do not edit manually

INSERT INTO nist_families (family_id, name, abbreviation) VALUES
  ('ac', 'Access Control', 'AC'),
  ('at', 'Awareness and Training', 'AT'),
  ('au', 'Audit and Accountability', 'AU'),
  ('ca', 'Assessment, Authorization, and Monitoring', 'CA'),
  ('cm', 'Configuration Management', 'CM'),
  ('cp', 'Contingency Planning', 'CP'),
  ('ia', 'Identification and Authentication', 'IA'),
  ('ir', 'Incident Response', 'IR'),
  ('ma', 'Maintenance', 'MA'),
  ('mp', 'Media Protection', 'MP'),
  ('pe', 'Physical and Environmental Protection', 'PE'),
  ('pl', 'Planning', 'PL'),
  ('pm', 'Program Management', 'PM'),
  ('ps', 'Personnel Security', 'PS'),
  ('pt', 'Personally Identifiable Information Processing and Transparency', 'PT'),
  ('ra', 'Risk Assessment', 'RA'),
  ('sa', 'System and Services Acquisition', 'SA'),
  ('sc', 'System and Communications Protection', 'SC'),
  ('si', 'System and Information Integrity', 'SI'),
  ('sr', 'Supply Chain Risk Management', 'SR');
