-- NIST SP 800-53 Catalog Version Record
-- Auto-generated by scripts/convert_nist_oscal.py — do not edit manually

INSERT INTO catalog_versions (catalog_name, version, source_hash, applied_at, migration_type, notes) VALUES
  ('nist-800-53', '5.2.0', '1645df6a370dcb931db2e2d5d70c2f77bc89c38499a416c23a70eb2c0e595bcc', NOW(), 'seed',
   'NIST SP 800-53 Rev 5 v5.2.0 — source last modified 2025-08-26T14:33:16.00000-00:00');
