-- Crosswalk: NIST AI RMF 1.0 → 800-53 Rev 5 SI (System and Information Integrity)
-- 38 mappings

INSERT INTO crosswalk_mappings (subcategory_id, control_id, coverage_level, rationale, guidance, evidence_types)
VALUES
  ('GOVERN 1.1', 'si-1', 'Partial', 'SI policy establishes integrity requirements applicable to AI systems', 'Reference AI-specific integrity requirements in SI policy', ARRAY['policy_documents']),
  ('GOVERN 1.3', 'si-1', 'Partial', 'SI procedures support AI system integrity processes', 'Include AI model integrity procedures', ARRAY['policy_documents']),
  ('MANAGE 1.2', 'si-2', 'Strong', 'Flaw remediation directly supports AI system patching and updates', 'Track AI model and pipeline vulnerabilities alongside traditional flaws', ARRAY['vulnerability_reports', 'patch_records']),
  ('MANAGE 1.3', 'si-2', 'Strong', 'Flaw remediation prioritization applies to AI-specific vulnerabilities', 'Prioritize flaws that affect AI model integrity or output reliability', ARRAY['vulnerability_reports']),
  ('MANAGE 4.1', 'si-2', 'Partial', 'Flaw remediation feeds AI risk monitoring', 'Include AI system flaws in remediation tracking dashboards', ARRAY['vulnerability_reports']),
  ('MANAGE 2.2', 'si-3', 'Partial', 'Malicious code protection supports AI system runtime integrity', 'Scan AI model artifacts and training data pipelines for malicious content', ARRAY['scan_reports']),
  ('MANAGE 2.4', 'si-3', 'Partial', 'Malicious code protection mitigates AI supply chain risks', 'Verify integrity of third-party AI libraries and pre-trained models', ARRAY['scan_reports']),
  ('MEASURE 2.4', 'si-4', 'Strong', 'System monitoring enables continuous measurement of AI system behavior', 'Monitor AI model inference patterns for anomalous outputs or drift', ARRAY['monitoring_logs', 'alert_records']),
  ('MEASURE 2.5', 'si-4', 'Strong', 'System monitoring supports AI output quality measurement', 'Track AI prediction accuracy, confidence scores, and error rates', ARRAY['monitoring_logs']),
  ('MEASURE 2.7', 'si-4', 'Strong', 'System monitoring captures AI system performance and fairness metrics', 'Include bias and fairness monitoring in system monitoring strategy', ARRAY['monitoring_logs', 'audit_reports']),
  ('MEASURE 2.8', 'si-4', 'Partial', 'System monitoring supports robustness measurement', 'Monitor AI system behavior under adversarial or edge-case conditions', ARRAY['monitoring_logs']),
  ('MEASURE 3.1', 'si-4', 'Strong', 'System monitoring enables ongoing AI measurement activities', 'Integrate AI-specific telemetry into SIEM and monitoring platforms', ARRAY['monitoring_logs', 'alert_records']),
  ('MEASURE 3.3', 'si-4', 'Partial', 'System monitoring feedback informs AI measurement improvements', 'Use monitoring trends to refine AI performance thresholds', ARRAY['monitoring_logs']),
  ('MANAGE 4.1', 'si-4', 'Strong', 'System monitoring feeds AI incident detection', 'Configure alerts for AI model degradation, drift, or unexpected behavior', ARRAY['monitoring_logs', 'alert_records']),
  ('MANAGE 4.2', 'si-4', 'Partial', 'System monitoring supports AI incident escalation', 'Route AI-specific monitoring alerts to appropriate response teams', ARRAY['monitoring_logs', 'alert_records']),
  ('MANAGE 4.1', 'si-5', 'Partial', 'Security alerts inform AI risk awareness', 'Include AI-specific vulnerability advisories in alert dissemination', ARRAY['alert_records']),
  ('MANAGE 4.2', 'si-5', 'Partial', 'Security advisories support AI incident communication', 'Distribute AI framework vulnerability notifications to stakeholders', ARRAY['alert_records']),
  ('MEASURE 2.5', 'si-6', 'Strong', 'Function verification validates AI system security controls operate correctly', 'Verify AI-specific security functions such as access controls on model endpoints', ARRAY['test_reports', 'audit_reports']),
  ('MEASURE 2.6', 'si-6', 'Strong', 'Function verification supports AI measurement validity', 'Validate that AI monitoring and measurement tools produce accurate results', ARRAY['test_reports']),
  ('MEASURE 2.5', 'si-7', 'Strong', 'Integrity verification ensures AI models and data have not been tampered with', 'Implement cryptographic hashing for AI model files and training datasets', ARRAY['integrity_reports']),
  ('MANAGE 2.2', 'si-7', 'Strong', 'Integrity monitoring detects unauthorized AI model or data modifications', 'Alert on unexpected changes to deployed model weights or configurations', ARRAY['integrity_reports', 'alert_records']),
  ('MANAGE 2.4', 'si-7', 'Partial', 'Integrity controls mitigate AI model tampering risks', 'Use code signing and checksums for AI deployment artifacts', ARRAY['integrity_reports']),
  ('MAP 2.3', 'si-10', 'Strong', 'Input validation directly relevant to AI system input data quality', 'Validate AI input data types, ranges, and formats before model inference', ARRAY['test_reports', 'validation_records']),
  ('MEASURE 2.5', 'si-10', 'Partial', 'Input validation supports AI output quality measurement', 'Track input validation failure rates as AI quality indicator', ARRAY['validation_records']),
  ('GOVERN 1.3', 'si-12', 'Partial', 'Information retention supports AI data governance lifecycle', 'Define retention policies for AI training data, model versions, and inference logs', ARRAY['policy_documents']),
  ('MAP 1.1', 'si-12', 'Partial', 'Retention management supports AI data inventory awareness', 'Track AI data assets through their retention lifecycle', ARRAY['data_inventory']),
  ('MANAGE 2.2', 'si-13', 'Strong', 'Predictable failure prevention directly applicable to AI system resilience', 'Design AI systems with failover and graceful degradation capabilities', ARRAY['architecture_documents', 'test_reports']),
  ('MANAGE 4.1', 'si-13', 'Partial', 'Failure prevention informs AI incident preparedness', 'Pre-plan responses for predicted AI system failure modes', ARRAY['incident_response_plans']),
  ('MAP 2.3', 'si-15', 'Direct', 'Output filtering directly controls AI system output quality and safety', 'Implement content filters, toxicity detectors, and hallucination checks on AI outputs', ARRAY['filter_configurations', 'test_reports']),
  ('MEASURE 2.11', 'si-15', 'Strong', 'Output filtering supports measurement of AI fairness and bias in outputs', 'Monitor filtered vs. unfiltered output distributions for bias indicators', ARRAY['monitoring_logs', 'audit_reports']),
  ('MAP 1.1', 'si-18', 'Strong', 'PII quality operations directly support AI training data quality', 'Ensure PII used in AI training is accurate, complete, and current', ARRAY['data_quality_reports']),
  ('MAP 1.2', 'si-18', 'Strong', 'PII quality management supports AI data categorization', 'Classify PII sensitivity levels in AI training and inference datasets', ARRAY['data_quality_reports']),
  ('MEASURE 2.1', 'si-18', 'Strong', 'PII quality operations support AI fairness measurement', 'Assess whether PII quality issues introduce bias in AI systems', ARRAY['data_quality_reports', 'audit_reports']),
  ('MAP 1.1', 'si-19', 'Strong', 'De-identification critical for AI training data privacy', 'Apply de-identification to PII before use in AI model training', ARRAY['privacy_reports']),
  ('MAP 1.2', 'si-19', 'Strong', 'De-identification supports proper AI data categorization', 'Verify de-identification effectiveness for AI training datasets', ARRAY['privacy_reports', 'test_reports']),
  ('GOVERN 1.4', 'si-19', 'Partial', 'De-identification supports AI privacy compliance', 'Reference de-identification standards in AI data governance policies', ARRAY['policy_documents']),
  ('MAP 1.1', 'si-22', 'Partial', 'Information diversity supports diverse AI training data', 'Use diverse data sources to reduce AI model bias', ARRAY['data_inventory']),
  ('MEASURE 2.1', 'si-22', 'Partial', 'Data diversity supports AI fairness assessment', 'Measure training data diversity as an AI fairness indicator', ARRAY['data_quality_reports'])
ON CONFLICT (subcategory_id, control_id) DO NOTHING;
