-- Crosswalk: NIST AI RMF 1.0 → 800-53 Rev 5 PM (Program Management)
-- 56 mappings

INSERT INTO crosswalk_mappings (subcategory_id, control_id, coverage_level, rationale, guidance, evidence_types)
VALUES
  ('GOVERN 1.1', 'pm-1', 'Strong', 'Information security program plan establishes AI governance foundation', 'Integrate AI risk management requirements into the information security program', ARRAY['policy_documents']),
  ('GOVERN 1.2', 'pm-1', 'Partial', 'Program plan supports AI accountability structures', 'Reference AI-specific roles and responsibilities in program plan', ARRAY['policy_documents']),
  ('GOVERN 1.3', 'pm-1', 'Partial', 'Program plan establishes AI risk management processes', 'Include AI lifecycle processes in security program plan', ARRAY['policy_documents']),
  ('GOVERN 2.1', 'pm-2', 'Direct', 'Security program leadership role directly maps to AI governance leadership', 'Designate senior official responsible for AI risk oversight', ARRAY['organizational_charts', 'role_descriptions']),
  ('GOVERN 2.2', 'pm-2', 'Strong', 'Program leadership supports AI competency requirements', 'Ensure security program leader has AI risk management expertise', ARRAY['role_descriptions', 'training_records']),
  ('GOVERN 1.5', 'pm-3', 'Strong', 'Resource allocation directly supports AI risk management funding', 'Allocate dedicated resources for AI risk assessment and monitoring', ARRAY['budget_documents']),
  ('GOVERN 1.7', 'pm-3', 'Strong', 'Resource planning supports AI program sustainability', 'Plan multi-year resource allocation for AI governance maturation', ARRAY['budget_documents']),
  ('MANAGE 1.1', 'pm-4', 'Strong', 'POA&M process directly supports AI risk treatment tracking', 'Track AI-specific risk mitigations in plan of action and milestones', ARRAY['poam_records']),
  ('MANAGE 1.2', 'pm-4', 'Strong', 'POA&M supports AI risk response prioritization', 'Prioritize AI risk items based on impact and likelihood', ARRAY['poam_records']),
  ('MANAGE 1.3', 'pm-4', 'Partial', 'POA&M tracks AI risk response progress', 'Include AI risk response milestones and completion criteria', ARRAY['poam_records']),
  ('MAP 1.1', 'pm-5', 'Strong', 'System inventory directly supports AI system identification', 'Include all AI systems and components in organizational inventory', ARRAY['asset_inventory']),
  ('MAP 1.5', 'pm-5', 'Strong', 'Inventory supports AI system benefit and impact identification', 'Document AI system purposes, stakeholders, and potential impacts', ARRAY['asset_inventory']),
  ('MAP 5.1', 'pm-5', 'Partial', 'Inventory supports AI documentation completeness', 'Ensure inventoried AI systems have complete documentation', ARRAY['asset_inventory']),
  ('MEASURE 4.1', 'pm-6', 'Strong', 'Performance measures directly support AI measurement effectiveness tracking', 'Define metrics to track AI risk management program effectiveness', ARRAY['performance_reports']),
  ('MEASURE 4.2', 'pm-6', 'Strong', 'Performance measures support AI measurement feedback loops', 'Use performance metrics to identify AI governance improvements', ARRAY['performance_reports']),
  ('GOVERN 1.1', 'pm-7', 'Partial', 'Enterprise architecture contextualizes AI system placement', 'Position AI systems within enterprise architecture documentation', ARRAY['architecture_documents']),
  ('GOVERN 1.1', 'pm-9', 'Strong', 'Risk strategy directly establishes AI risk management approach', 'Include AI-specific risk categories in organizational risk strategy', ARRAY['risk_management_plans']),
  ('GOVERN 1.3', 'pm-9', 'Strong', 'Risk strategy defines AI risk tolerance and acceptance criteria', 'Define risk appetite for AI system deployment and operation', ARRAY['risk_management_plans']),
  ('MAP 1.4', 'pm-9', 'Strong', 'Risk strategy provides framework for AI risk identification', 'Use risk strategy to scope AI risk assessments', ARRAY['risk_management_plans']),
  ('GOVERN 4.1', 'pm-10', 'Strong', 'Authorization process supports AI system approval governance', 'Require formal authorization for AI system deployment', ARRAY['authorization_records']),
  ('GOVERN 4.2', 'pm-10', 'Strong', 'Authorization process establishes AI deployment decision criteria', 'Define authorization criteria specific to AI system risks', ARRAY['authorization_records']),
  ('GOVERN 1.1', 'pm-11', 'Partial', 'Business process definition contextualizes AI system roles', 'Identify where AI systems support mission and business processes', ARRAY['policy_documents']),
  ('MAP 1.6', 'pm-11', 'Strong', 'Business process definition supports AI impact scoping', 'Map AI systems to affected mission and business processes', ARRAY['impact_assessments']),
  ('GOVERN 2.1', 'pm-13', 'Strong', 'Workforce development directly supports AI competency building', 'Include AI risk management in security and privacy workforce development', ARRAY['training_records', 'workforce_plans']),
  ('GOVERN 2.2', 'pm-13', 'Strong', 'Workforce planning addresses AI skill requirements', 'Identify AI-specific competencies needed in security workforce', ARRAY['workforce_plans']),
  ('GOVERN 3.2', 'pm-13', 'Strong', 'Workforce development includes AI training programs', 'Develop AI literacy and AI risk management training curricula', ARRAY['training_records']),
  ('MEASURE 1.1', 'pm-14', 'Strong', 'Testing and monitoring directly support AI measurement approaches', 'Include AI system testing in organizational testing strategy', ARRAY['test_reports']),
  ('MEASURE 1.2', 'pm-14', 'Strong', 'Testing programs validate AI measurement methods', 'Test AI-specific measurement tools and processes', ARRAY['test_reports']),
  ('MEASURE 1.3', 'pm-14', 'Partial', 'Monitoring supports ongoing AI measurement', 'Include AI metrics in continuous monitoring programs', ARRAY['monitoring_logs']),
  ('MEASURE 4.1', 'pm-14', 'Strong', 'Testing validates AI measurement program effectiveness', 'Assess whether AI testing achieves measurement objectives', ARRAY['test_reports', 'performance_reports']),
  ('GOVERN 5.1', 'pm-15', 'Partial', 'Security groups support AI community engagement', 'Participate in AI safety and governance professional communities', ARRAY['meeting_records']),
  ('GOVERN 5.2', 'pm-15', 'Partial', 'Association contacts support AI standards awareness', 'Monitor AI governance standards from industry groups', ARRAY['meeting_records']),
  ('MAP 3.1', 'pm-16', 'Partial', 'Threat awareness supports AI threat identification', 'Include AI-specific threats in threat awareness program', ARRAY['threat_reports']),
  ('MAP 3.3', 'pm-16', 'Partial', 'Threat awareness supports AI risk context understanding', 'Disseminate AI attack technique information to stakeholders', ARRAY['threat_reports']),
  ('GOVERN 5.1', 'pm-20', 'Strong', 'Privacy program dissemination supports AI transparency', 'Communicate AI data processing practices to stakeholders', ARRAY['privacy_notices']),
  ('MANAGE 4.3', 'pm-20', 'Strong', 'Privacy information dissemination supports AI accountability reporting', 'Publish AI system privacy impact information', ARRAY['privacy_notices', 'public_reports']),
  ('MAP 1.1', 'pm-22', 'Strong', 'PII quality management directly supports AI training data quality', 'Ensure PII accuracy in datasets used for AI training and evaluation', ARRAY['data_quality_reports']),
  ('MEASURE 2.1', 'pm-22', 'Strong', 'PII quality supports AI fairness and bias measurement', 'Assess whether PII quality issues affect AI model fairness', ARRAY['data_quality_reports', 'audit_reports']),
  ('MAP 1.1', 'pm-25', 'Strong', 'PII minimization directly applicable to AI training data', 'Minimize PII in AI training, testing, and research datasets', ARRAY['privacy_reports']),
  ('GOVERN 1.4', 'pm-25', 'Partial', 'PII minimization supports AI privacy compliance', 'Reference data minimization in AI data governance policies', ARRAY['policy_documents']),
  ('MANAGE 4.2', 'pm-26', 'Strong', 'Complaint management directly supports AI user feedback', 'Include AI-related complaints in complaint management process', ARRAY['complaint_records']),
  ('MANAGE 4.3', 'pm-26', 'Strong', 'Complaint tracking supports AI accountability', 'Report AI complaint trends and resolution outcomes', ARRAY['complaint_records', 'public_reports']),
  ('GOVERN 5.2', 'pm-27', 'Strong', 'Privacy reporting supports AI governance transparency', 'Include AI system privacy metrics in organizational reporting', ARRAY['public_reports']),
  ('MANAGE 4.3', 'pm-27', 'Strong', 'Privacy reporting supports AI accountability', 'Report AI-related privacy incidents and mitigations', ARRAY['public_reports']),
  ('GOVERN 1.1', 'pm-28', 'Direct', 'Risk framing directly establishes AI risk context and boundaries', 'Frame AI risks within organizational risk tolerance and assumptions', ARRAY['risk_management_plans']),
  ('MAP 1.4', 'pm-28', 'Direct', 'Risk framing directly supports AI risk identification scope', 'Use risk framing to scope AI risk assessments and priorities', ARRAY['risk_management_plans']),
  ('MAP 1.5', 'pm-28', 'Partial', 'Risk framing supports AI benefit-cost analysis', 'Frame AI benefits and risks in organizational context', ARRAY['risk_management_plans']),
  ('GOVERN 2.1', 'pm-29', 'Strong', 'Risk management leadership supports AI governance structure', 'Include AI risk management in senior leadership responsibilities', ARRAY['organizational_charts', 'role_descriptions']),
  ('GOVERN 2.3', 'pm-29', 'Strong', 'Risk management roles support AI accountability', 'Define accountability for AI risk management decisions', ARRAY['role_descriptions']),
  ('MAP 3.4', 'pm-30', 'Direct', 'Supply chain risk strategy directly applies to AI supply chain', 'Address AI model and data supply chain risks in SCRM strategy', ARRAY['risk_management_plans']),
  ('MAP 3.5', 'pm-30', 'Strong', 'SCRM strategy supports AI third-party risk management', 'Include AI vendor and model provider risks in supply chain strategy', ARRAY['risk_management_plans']),
  ('MEASURE 3.1', 'pm-31', 'Strong', 'Continuous monitoring directly supports ongoing AI measurement', 'Include AI system metrics in continuous monitoring strategy', ARRAY['monitoring_plans']),
  ('MEASURE 3.2', 'pm-31', 'Strong', 'Monitoring strategy supports AI measurement updates', 'Define triggers for AI measurement recalibration', ARRAY['monitoring_plans']),
  ('MANAGE 4.1', 'pm-31', 'Strong', 'Continuous monitoring supports AI incident detection', 'Configure AI-specific continuous monitoring indicators', ARRAY['monitoring_plans', 'alert_records']),
  ('MAP 2.1', 'pm-32', 'Direct', 'Purposing directly defines intended AI system uses', 'Document authorized purposes for AI system deployment and use', ARRAY['policy_documents']),
  ('MAP 2.2', 'pm-32', 'Direct', 'Purposing directly limits AI system scope', 'Define boundaries for AI system operation and decision-making', ARRAY['policy_documents'])
ON CONFLICT (subcategory_id, control_id) DO NOTHING;
